2018-02-13 16:14:57 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Table "USER_ROLE" not found; SQL statement:
SELECT * FROM USER_Role [42102-196]
2018-02-13 16:15:11 jdbc[14]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "USER_ROLES[*] USER_ROLES USER_ROLES"; expected "UPDATE, USE, {"; SQL statement:
USER_ROLES USER_ROLES USER_ROLES [42001-196]
2018-02-14 14:26:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "AUTHORITIES" not found; SQL statement:
select username,authority from authorities where username = ? [42102-196]
2018-02-22 00:16:51 jdbc[3]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-196]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:185)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:127)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
	at com.zaxxer.hikari.pool.HikariPool.access$200(HikariPool.java:70)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:696)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:682)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2018-02-22 13:53:45 jdbc[13]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "TASK[*]"; expected "TRUNCATE, {"; SQL statement:
TASK [42001-196]
